# Cấu hình hiển thị
# display-type: ACTIONBAR hoặc SCOREBOARD hoặc BOTH
settings:
  display-type: SCOREBOARD
  scoreboard-title: "&b&lRANDOM SPEEDRUN"

# Các tính năng nâng cao
features:
  random-gui: true
  countdown: true
  victory-fireworks: true
  victory-sound: true
  victory-particles: true
  broadcast-winner: true

# Cấu hình hệ thống thế giới biệt lập
worlds:
# Tên folder world mẫu
  template-name: "template_world"  
  # Số lượng world chạy tối đa cùng lúc  
  max-concurrent: 30                
  # Phạm vi ngẫu nhiên khi spawn (block)
  random-range: 5000                
  # Thời gian chờ sau khi thắng (giây)
  finish-delay: 5                   

# Cấu hình lưu trữ dữ liệu
database:
# SQLITE hoặc MYSQL
  type: "MYSQL"         
  mysql:
    host: "localhost"
    port: 3306
    database: "speedrun"
    username: "root"
    password: ""